### ISSUE TITLE
mimosa bower command won't work with version specific module

### ISSUE THREAD

**Issue by scribeGriff** [dbashford/mimosa-bower#46]
I'm trying to make use of the ```strategy: "together"```, but find if I do this
```
exports.config = {
  "modules": [
    "copy",
    "bower@1.8.1"
  ],
```
and then execute ```mimosa bower```, I get
ERROR - You have called the bower command on a project that does not have bower included.

But if I use (from a clean install):
```
exports.config = {
  "modules": [
    "copy",
    "bower"
  ],
```
and then execute ```mimosa bower```, I get
ERROR - Unable to start Mimosa for the following reason(s):
 * Invalid bower.copy.strategy used. Must be "none", "vendorRoot" or "packageRoot".

My current work around is to do the first one, which installs verson 1.8.1 in node_modules, and then change the config file to the second one and run ```mimosa bower``` again.  That works, but is there a cleaner way to do this?

**Comment by dbashford** [comment]
The problem is likely because of a conflict between the mimosa-bower installed inside mimosa and the one you are trying to use locally. The short-term fix, while we all wait for me to wrap up the next big release, is to remove the possible conflict.

Could you try `mimosa mod:uninstall mimosa-bower`, and then put the `@1.8.1` in the mimosa config? That will remove the one installed inside mimosa and force Mimosa to use yours.

If that doesn't work, remove mimosa-bower from your projects `node_modules` and then run `mimosa mod:install mimosa-bower@1.8.1`.  That will update the one installed inside Mimosa to the version you need.

Let me know how that goes?

**Comment by dbashford** [comment]
I should point out, the erroneous error message `You have called the bower command on a project that does not have bower included` is fixed already in `1.8.1`.  I was only checking for `bower` or `mimosa-bower` in the modules array rather than `indexOf('bower') == 0` which would let the version specificity work.

**Comment by scribeGriff** [comment]
After uninstalling, mimosa just quits with ```bower is not a valid command```, but reinstalling with version 1.8.1 works and no longer even requires the version number in the config file, which is nice.  And checking with ```npm list -g mimosa-bower``` shows 1.8.1 is installed under mimosa.  So it seems as long as I don't update mimosa until the dependencies are updated, I guess in the big next release (I'm at 2.3.26) , it seems I should be fine.  Thanks!

**Comment by dbashford** [comment]
The next major release will remove the concept of built in modules.  Mimosa won't ship with its own modules.  So it'll alleviate this issue straight away.

**Comment by scribeGriff** [comment]
That sounds like a great approach, looking forward to that release.  Closing this since, as you pointed out, version 1.8.1 doesn't have this issue.  Thanks again.
